import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "../styles/globals.css"
import Navbar from "@/components/Navbar";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import Burger from "@/components/Burger"


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ['400', '500', '600','700'], 
  style: ['normal', 'italic'],
 
});


export const metadata: Metadata = {
  title: "Farengeyt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter}`}>
        <Navbar/>
         <Header />   
         {children} 
         <Footer />      
      </body>
    </html>
  );
}
